import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Providers } from "./providers";
import { Toaster } from "@/components/ui/toaster";
import { CartProvider } from "../context/CartContext";
import ThemeProvider from "@/components/theme-provider";
import { WishlistProvider } from "@/context/WishlistContext";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <Providers>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <CartProvider>
              <WishlistProvider>
                <Navbar />
                {children}
                <Script
                  src="https://js.paystack.co/v1/inline.js"
                  strategy="beforeInteractive"
                />
                <Footer />
                <Toaster />
              </WishlistProvider>
            </CartProvider>
          </ThemeProvider>
        </body>
      </Providers>
    </html>
  );
}
